# Generated by Django 4.0.6 on 2022-08-22 09:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('amazontrackingsite', '0003_remove_productinstance_follower'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amazonpage',
            name='follower',
        ),
        migrations.CreateModel(
            name='FollowedAmazonPages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='amazontrackingsite.amazonpage')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
